[package]
name = "pssh"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
futures = "0.3.31"
notify = "8.0.0"
openssh = "0.11.5"
openssh-sftp-client = "0.15.2"
tokio = { version = "1.44.1", features = ["full"] }
